FORMAT: 1A
HOST: http://tpeoc-feedback.azurewebsites.net/

# eoc_feedback

臺北市政府EOC案件回報API

## Feedback [/feedback]

### 列出所有回報資料 [GET]

+ Response 200 (application/json)

        [
            {
                "DPName": "0531地震",
                "CaseSN": 2,
                "description": "test",
                "solve_suggest": 1,
                "photo_link": [
                    "http://www.example.com/example.png",
                    "http://www.example.com/example2.png"
                ],
                "video_link": [],
                "reporter": null
            }
        ]

### 新增回報資料 [POST]

+ Request (application/json)
        
    欄位說明
        
    + `CaseSN` EOC案件流水編號
    + `description` 回報訊息描述
    + `solve_suggest` 事件已排除建議(True or False)
    + `photo_link` (optional) 圖片連結(array)
    + `video_link` (optional) 影片連結(array)
    + `reporter` (optional) 回報者
    
    + Body
    
            {
                "CaseSN": 1,
                "description": "test",
                "solve_suggest": true,
                "photo_link": [
                    "http://example.com/pic1.jpg"
                ],
                "video_link": [
                    "http://youtube.com/aaa",
                    "http://youtube.com/bbb"
                ],
                "reporter": "TPEOC"
            }

+ Response 200 (application/json)

    + Body

            {
                "message": "Insert succeed."
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "invalid CaseSN"
            }

## Feedback [/feedback/{CaseSN}]

+ Parameters
    + CaseSN (number) - Serial number iof EOC in the form of an integer

### 列出單一案件回報資料 [GET]

+ Response 200 (application/json)

        [
            {
                "DPName": "0531地震",
                "CaseSN": 2,
                "description": "test",
                "solve_suggest": 1,
                "photo_link": [
                    "http://www.example.com/example.png",
                    "http://www.example.com/example2.png"
                ],
                "video_link": [],
                "reporter": null
            }
        ]